language: r
warnings_are_errors: true
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    
env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5

before_install:
  - cd ./ranger-r-package/ranger

r:
  - oldrel
  - release
  - devel
  
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls(quiet = FALSE)'

notifications:
  email:
    recipients:
        - work@wrig.de
    on_success: change
    on_failure: change
